services:
  app:
    build:
      context: .
      target: development
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: commerce_stock_test
      DB_USERNAME: commerce_stock
      DB_PASSWORD: commerce_stock
    volumes:
      - .:/var/www
      - ../..:/var/pkg
      - ${HOME}/.config/composer/auth.json:/home/laravel/.composer/auth.json:ro
      - ${HOME}/.config/composer/auth.json:/config/composer/auth.json:ro

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: commerce_stock_test
      POSTGRES_USER: commerce_stock
      POSTGRES_PASSWORD: commerce_stock
    ports:
      - "54229:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
